services:
  db:
    image: mysql:8.0.36
    container_name: db
    environment:
      MYSQL_DATABASE: iot_sensor_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - iot-sensor-db:/var/lib/mysql

  redis:
    image: redis:8.2.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - iot-sensor-redis:/data

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - iot-sensor-prometheus:/prometheus

  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - iot-sensor-grafana:/var/lib/grafana

volumes:
  iot-sensor-db:
  iot-sensor-redis:
  iot-sensor-prometheus:
  iot-sensor-grafana: