global:
  scrape_interval: 5m

scrape_configs:
  - job_name: "iot-sensor-data-platform"

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets: [ "host.docker.internal:8081" ]

        labels:
          application: "iot-sensor-data-platform"